services:
  - type: web
    name: pdf-to-book-creator-v2
    env: node
    plan: free
    buildCommand: "npm install && npx vite build"
    startCommand: "node start.js"
    envVars:
      - key: NODE_VERSION
        value: "18.18.0"
      - key: DEPLOY_TAG
        value: "force-redeploy-2025-08-25-4"
      - key: VITE_LULU_CLIENT_ID
        fromGroup: lulu-api-keys
      - key: VITE_LULU_CLIENT_SECRET
        fromGroup: lulu-api-keys
      - key: VITE_LULU_API_BASE
        value: https://api.lulu.com/v1
      - key: VITE_OPENAI_API_KEY
        fromGroup: openai-api-key
      - key: VITE_DEV_MODE
        value: false
      - key: LULU_CLIENT_ID
        fromGroup: lulu-api-keys
      - key: LULU_CLIENT_SECRET
        fromGroup: lulu-api-keys
      - key: LULU_API_BASE
        value: https://api.lulu.com/v1
